name: Close Invalid Issue

on:
    issues:
        types:
            - labeled

jobs:
    closeIssue:
        if: github.event.label.name == 'invalid'
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
            - name: Close Issue
              env:
                  GH_TOKEN: ${{ github.token }}
                  GH_REPO: ${{ github.repository }}
                  ISSUE_NUMBER: ${{ github.event.issue.number }}
              run: >
                  gh issue close "$ISSUE_NUMBER"
                  --repo "$GH_REPO"
                  --comment "This issue is invalid. Please conform to the issue templates."
                  --reason "not planned"
